### ISSUE TITLE
Refactor grouping state

### ISSUE THREAD

**Issue by mrMakaronka** [flame-stream/FlameStream#22]
**Предыстория:**

В группировке входящие элементы попадают в специальные корзины по хешам. При этом элементы внутри корзины должны быть отсортированы по мете. Важный момент: если мы в корзине находим элементы, которые новый поступивший элемент инвалидирует – мы их из корзины удаляем. 

**Проблемы:**

1. Вышеописанная логика также должна быть реализована в барьере. Хочется не дублировать код, при этом сохраняя его логичность. Сейчас в [барьере](https://github.com/flame-stream/FlameStream/blob/master/core/src/main/java/com/spbsu/flamestream/core/graph/barrier/collector/LinearCollector.java#L31) вызывается статический метод insert из групинга – решение, которое хочется заменить чем-то более изящным.
2. В группировке сами корзины отдает класс [GroupingState](https://github.com/flame-stream/FlameStream/blob/master/core/src/main/java/com/spbsu/flamestream/core/graph/ops/state/GroupingState.java), который имеет странный интерфейс (например, он предполагает, что мы отдаем наружу изменяемый List). Более того, все его методы используются только один раз. Опять же хочется как-то поправить этот код, чтобы было не стыдно показывать.

**Comment by marnikitta** [comment]
Fixed
