### ISSUE TITLE
Add ability to disable statistics

### ISSUE THREAD

**Issue by mrMakaronka** [flame-stream/FlameStream#63]
Some statistics can cause extra overhead. It would be useful to have, e.g. config param for enabling/disabling statistics.

**Comment by marnikitta** [comment]
Obsolete, replaced with [tracing](https://github.com/flame-stream/FlameStream/blob/d56cd76ae1c28603fb1c03688748f2f63c4c550b/runtime/src/main/java/com/spbsu/flamestream/runtime/utils/tracing/Tracing.java), which can be enabled by JVM params
