### ISSUE TITLE
OOM during tests

### ISSUE THREAD

**Issue by marnikitta** [flame-stream/FlameStream#69]
Build randomly fails.

[log.txt](https://github.com/flame-stream/FlameStream/files/1433472/log.txt)

**Comment by mrMakaronka** [comment]
It seems that ArrayIndexOutOfBoundsException is a result. The cause is OutOfMemoryError.

**Comment by marnikitta** [comment]
Again
[oom.txt](https://github.com/flame-stream/FlameStream/files/1436818/oom.txt)

OOM was happening from time to time at AWS, when we were benchmarking.

I have noticed that this error appeared after the [chaincall fix](https://github.com/flame-stream/FlameStream/commit/f67aadcfc4c0ddad733da148e68086a04c0ea099) in the grouping.

**Comment by mrMakaronka** [comment]
An interesting observation: first error [log.txt](https://github.com/flame-stream/FlameStream/files/1433472/log.txt) contains OutOfBounds exception right before OOM inside TObjectLongHashMap within BarrierStatistics. The index is 83430029,  it means  that underlying array occupies at least ~300mb.

**Comment by mrMakaronka** [comment]
Local comparison of memory consumption between versions with and without [chaincall fix](https://github.com/flame-stream/FlameStream/commit/f67aadcfc4c0ddad733da148e68086a04c0ea099) does not show significant difference. Disabling [BarrierStatistics](https://github.com/flame-stream/FlameStream/blob/master/core/src/main/java/com/spbsu/flamestream/core/graph/barrier/BarrierStatistics.java) does not improve anything as well.

**Comment by mrMakaronka** [comment]
Right before the OOM, log contains `Fronts fetched: [5223, 5224, 5225, 5226, 5227]`. Therefore, it seems that the failed test is [GroupingAcceptanceTest](https://github.com/flame-stream/FlameStream/blob/master/runtime/src/test/java/com/spbsu/flamestream/runtime/GroupingAcceptanceTest.java), because it is the only test with 5 workers.

**Comment by marnikitta** [comment]
Fixed: 34f560b7e12ce49440a9af44ea5ad2def4bf6aea
