### ISSUE TITLE
Move the front into graph

### ISSUE THREAD

**Issue by marnikitta** [flame-stream/FlameStream#72]
- Separate source and front logic
- Replace reports with watermark

Reports replacement seems to solve the "sync global time assignment" problem.

**Comment by mrMakaronka** [comment]
Introducing low watermarks: [Google MillWheel](http://db.cs.berkeley.edu/cs286/papers/millwheel-vldb2013.pdf)

Flink documentation on [EventTime](https://ci.apache.org/projects/flink/flink-docs-release-1.3/dev/event_time.html)

**Comment by marnikitta** [comment]
[Punctuations](https://scholar.google.ru/scholar?cluster=11608121660665672927&hl=en&as_sdt=0,5&scilib=1)

**Comment by marnikitta** [comment]
[Flexible time management in data stream systems](https://scholar.google.com/scholar?cluster=15564704761549403347&hl=en&as_sdt=0,5)

**Comment by marnikitta** [comment]
We could separate fronts in two units: `Front` and `Source`. `Fronts` generate events and submit them to `Source`. `Source` assignes `Meta`. In case of front failures, the is no way to replay items with the same global time.

The problem is not new, e.g. Flink solves it using the two different notions of time:

- Ingestion time
- Event time

Event time introduces additional latencies. Ingestion time can't handle replay.

**Comment by marnikitta** [comment]
[The Dataflow Model: A Practical Approach to Balancing Correctness, Latency, and Cost in Massive-Scale, Unbounded, Out-of-Order Data Processing](https://scholar.google.ru/scholar?cluster=7054720938398035170&hl=en&as_sdt=0,5)
